<?php
$eZTranslationCacheCodeDate = 1058863428;

$CacheInfo = array (
  'charset' => 'utf-8',
);
$TranslationInfo = array (
  'context' => 'design/admin/ajaxuploader',
);

$TranslationRoot = array (
  '07fc90ce8775821e3afe3ae303787689' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Go to the parent level',
    'comment' => NULL,
    'translation' => 'Vai al nodo genitore',
    'key' => '07fc90ce8775821e3afe3ae303787689',
  ),
  '64adebb263ca6e5e4f890c141b1b83e2' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Step 1/3: Upload a file',
    'comment' => NULL,
    'translation' => 'Passo 1/3: Carica un file',
    'key' => '64adebb263ca6e5e4f890c141b1b83e2',
  ),
  'c32b834266bfbd9b7d0e40df2d2f3ee5' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Name',
    'comment' => NULL,
    'translation' => 'Nome',
    'key' => 'c32b834266bfbd9b7d0e40df2d2f3ee5',
  ),
  'f537beb4c65e60bae251fb4ecb3bd8ac' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Type',
    'comment' => NULL,
    'translation' => 'Tipo',
    'key' => 'f537beb4c65e60bae251fb4ecb3bd8ac',
  ),
  '655940c9592a436760146d4601e9d97d' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Section',
    'comment' => NULL,
    'translation' => 'Sezione',
    'key' => '655940c9592a436760146d4601e9d97d',
  ),
  '58374ad0ab4983ef5535fe398d458efa' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'prev',
    'comment' => NULL,
    'translation' => 'prec',
    'key' => '58374ad0ab4983ef5535fe398d458efa',
  ),
  '2831055ce77278f2f35187c0df9ab378' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'next',
    'comment' => NULL,
    'translation' => 'succ',
    'key' => '2831055ce77278f2f35187c0df9ab378',
  ),
  'd15a56a2cbc98dbc4b83152975758ca2' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Step 2/3: Choose a location for the new \'%class\' object',
    'comment' => NULL,
    'translation' => 'Passo 2/3: Scegli una nuova collocazione per il nuovo oggetto \'%class\'',
    'key' => 'd15a56a2cbc98dbc4b83152975758ca2',
  ),
  '4dd7537372fed628379e365b58822de6' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Please choose a location for the \'%class\' object that is going to be created from it.',
    'comment' => NULL,
    'translation' => 'Scegli una collocazione per il nuovo oggetto \'%class\' che ne viene creato.',
    'key' => '4dd7537372fed628379e365b58822de6',
  ),
  '02fd9b04a0cd4165c014587882519b77' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Choose this location',
    'comment' => NULL,
    'translation' => 'Scegli questa collocazione',
    'key' => '02fd9b04a0cd4165c014587882519b77',
  ),
  'd25c2f75d6958fe68b8b2d0d1f27c448' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Close',
    'comment' => NULL,
    'translation' => 'Chiudi',
    'key' => 'd25c2f75d6958fe68b8b2d0d1f27c448',
  ),
  '71863c797b16cd790ac145bd0994bec7' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Step 3/3: Preview of \'%name\' (%class)',
    'comment' => NULL,
    'translation' => 'Passo 3/3: Anteprima del \'%name\' (%class)',
    'key' => '71863c797b16cd790ac145bd0994bec7',
  ),
  '7b78cab55dfbfa0b5f1b7d2a660923ee' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Add',
    'comment' => NULL,
    'translation' => 'Aggiungi',
    'key' => '7b78cab55dfbfa0b5f1b7d2a660923ee',
  ),
  '822c2b0c162d1a648aabf45ac0bd0c23' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'File',
    'comment' => NULL,
    'translation' => 'File',
    'key' => '822c2b0c162d1a648aabf45ac0bd0c23',
  ),
  '0c2ad536d03cb25c2a78a8fa353ee864' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Required',
    'comment' => NULL,
    'translation' => 'Obbligatorio',
    'key' => '0c2ad536d03cb25c2a78a8fa353ee864',
  ),
  '96b2c4ab2dab1de9e5ab81e6e1cbb8b8' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'The name will be autogenerated',
    'comment' => NULL,
    'translation' => 'Il nome verrà generato automaticamente',
    'key' => '96b2c4ab2dab1de9e5ab81e6e1cbb8b8',
  ),
  'b9c0f1c0910c765797e8d28f6bb18a84' => 
  array (
    'context' => 'design/admin/ajaxuploader',
    'source' => 'Upload the file',
    'comment' => NULL,
    'translation' => 'Carica file',
    'key' => 'b9c0f1c0910c765797e8d28f6bb18a84',
  ),
);
?>
